const QUESTION_SETS = {
  sport: [
    ["Which venue traditionally hosts the Boxing Day Test in Australia?", "Melbourne Cricket Ground", ["Sydney Cricket Ground", "Adelaide Oval", "The Gabba"]],
    ["The Ashes is a cricket rivalry between Australia and which country?", "England", ["India", "New Zealand", "South Africa"]],
    ["What was Don Bradman's Test batting average?", "99.94", ["89.94", "100.00", "109.94"]],
    ["Which Australian athlete won the women's 400 metres at the Sydney 2000 Olympics?", "Cathy Freeman", ["Sally Pearson", "Jane Saville", "Nova Peris"]],
    ["Which sport is Ian Thorpe best known for?", "Swimming", ["Cycling", "Athletics", "Rowing"]],
    ["The Melbourne Cup is run over what distance?", "3200 metres", ["1600 metres", "2400 metres", "4000 metres"]],
    ["Which city hosts the Australian Open tennis tournament?", "Melbourne", ["Sydney", "Brisbane", "Perth"]],
    ["In Australian rules football, how many points is a goal worth?", "Six", ["One", "Three", "Four"]],
    ["In rugby league, how many points is a try worth?", "Four", ["Three", "Five", "Six"]],
    ["In rugby union, how many points is a try worth?", "Five", ["Two", "Four", "Seven"]],
    ["Which medal is awarded to the AFL's best and fairest player in the home-and-away season?", "Brownlow Medal", ["Norm Smith Medal", "Coleman Medal", "Jock McHale Medal"]],
    ["Which award recognises the NRL's player of the year?", "Dally M Medal", ["Clive Churchill Medal", "Wally Lewis Medal", "Ken Irvine Medal"]],
    ["Which team nickname belongs to Australia's men's national football team?", "Socceroos", ["Wallabies", "Kookaburras", "Boomers"]],
    ["Which team nickname belongs to Australia's women's national football team?", "Matildas", ["Diamonds", "Opals", "Jillaroos"]],
    ["Which team nickname belongs to Australia's men's rugby union team?", "Wallabies", ["Kangaroos", "Socceroos", "Boomers"]],
    ["Which team nickname belongs to Australia's national netball team?", "Diamonds", ["Opals", "Matildas", "Hockeyroos"]],
    ["Which national men's hockey team is known as the Kookaburras?", "Australia", ["New Zealand", "England", "South Africa"]],
    ["Which national women's hockey team is known as the Hockeyroos?", "Australia", ["Canada", "Ireland", "India"]],
    ["Which Australian cyclist won the Tour de France in 2011?", "Cadel Evans", ["Robbie McEwen", "Stuart O'Grady", "Simon Gerrans"]],
    ["Which Australian soccer player is famous for captaining the Matildas and starring as a striker?", "Sam Kerr", ["Ellyse Perry", "Alyssa Healy", "Stephanie Gilmore"]],
    ["Which Australian basketballer was a WNBA MVP and a Seattle Storm champion?", "Lauren Jackson", ["Liz Cambage", "Penny Taylor", "Michele Timms"]],
    ["What type of bowling was Shane Warne famous for?", "Leg spin", ["Fast bowling", "Off spin", "Left-arm seam"]],
    ["The Allan Border Medal is awarded in which sport?", "Cricket", ["Rugby league", "Australian rules football", "Tennis"]],
    ["AFLW is the women's competition for which sport?", "Australian rules football", ["Rugby union", "Basketball", "Football"]],
    ["The Stawell Gift is a famous race in which sport?", "Athletics", ["Cycling", "Horse racing", "Swimming"]],
    ["Sydney hosted the Summer Olympics in which year?", "2000", ["1988", "1996", "2004"]],
    ["Which motorsport race is held at Mount Panorama?", "Bathurst 1000", ["Australian Grand Prix", "Indy 500", "Le Mans 24 Hours"]],
    ["The Australian Formula 1 Grand Prix is held at which Melbourne parkland circuit?", "Albert Park", ["Calder Park", "Sandown", "Phillip Island"]],
    ["The Sydney to Hobart yacht race traditionally starts on which day?", "Boxing Day", ["New Year's Day", "Australia Day", "Anzac Day"]],
    ["Which yacht ended the New York Yacht Club's long America's Cup winning streak in 1983?", "Australia II", ["Wild Oats XI", "Kookaburra", "Black Jack"]],
    ["What is the national domestic first-class cricket competition in Australia called?", "Sheffield Shield", ["Big Bash League", "Marsh Cup", "Border-Gavaskar Trophy"]],
    ["What format is played in the Big Bash League?", "Twenty20 cricket", ["Test cricket", "One-day cricket", "Indoor cricket"]],
    ["The Bledisloe Cup is contested by Australia and which country?", "New Zealand", ["England", "France", "South Africa"]],
    ["Which AFL club is nicknamed the Magpies?", "Collingwood", ["Carlton", "Essendon", "Richmond"]],
    ["Which NRL club is based in Auckland?", "New Zealand Warriors", ["Canberra Raiders", "Melbourne Storm", "Gold Coast Titans"]],
    ["Which NRL team is nicknamed the Broncos?", "Brisbane", ["Parramatta", "Penrith", "Cronulla"]],
    ["Which Australian tennis player completed two calendar-year Grand Slams?", "Rod Laver", ["Pat Rafter", "Lleyton Hewitt", "John Newcombe"]],
    ["Which Australian tennis champion was born Evonne Goolagong?", "Evonne Goolagong Cawley", ["Margaret Court", "Ash Barty", "Sam Stosur"]],
    ["Which arena is the main stadium for the Australian Open?", "Rod Laver Arena", ["John Cain Arena", "Margaret Court Arena", "Ken Rosewall Arena"]],
    ["Which Australian won the 2022 Australian Open women's singles title?", "Ash Barty", ["Sam Stosur", "Ajla Tomljanovic", "Daria Saville"]],
    ["Which sport uses the term 'behind' for a one-point score?", "Australian rules football", ["Rugby league", "Cricket", "Netball"]],
    ["How many players are on the field for each AFL team during play?", "18", ["11", "13", "15"]],
    ["How many players are on the field for each rugby league team?", "13", ["11", "15", "18"]],
    ["How many players are on court for each netball team?", "7", ["5", "6", "9"]],
    ["The Clive Churchill Medal is awarded after which event?", "NRL Grand Final", ["AFL Grand Final", "Melbourne Cup", "Australian Open final"]],
    ["The Norm Smith Medal is awarded after which event?", "AFL Grand Final", ["NRL Grand Final", "State of Origin", "Bledisloe Cup"]],
    ["Which cricket trophy is contested in Test series between Australia and India?", "Border-Gavaskar Trophy", ["Frank Worrell Trophy", "Chappell-Hadlee Trophy", "Trans-Tasman Trophy"]],
    ["Which trophy is contested in one-day cricket between Australia and New Zealand?", "Chappell-Hadlee Trophy", ["Ashes urn", "Border-Gavaskar Trophy", "Sheffield Shield"]],
    ["Which national team is known as the Australian Boomers?", "Men's basketball", ["Men's hockey", "Women's netball", "Men's rugby league"]],
    ["Which national team is known as the Australian Opals?", "Women's basketball", ["Women's football", "Women's hockey", "Women's rugby union"]]
  ],
  music: [
    ["Which Australian band released 'Highway to Hell'?", "AC/DC", ["INXS", "Cold Chisel", "Midnight Oil"]],
    ["Which AC/DC guitarist is known for wearing a school uniform on stage?", "Angus Young", ["Malcolm Young", "Bon Scott", "Phil Rudd"]],
    ["Who was the lead singer of INXS?", "Michael Hutchence", ["Jimmy Barnes", "Peter Garrett", "John Farnham"]],
    ["Which band had a global hit with 'Down Under'?", "Men at Work", ["Crowded House", "Australian Crawl", "Mental As Anything"]],
    ["Which Midnight Oil song includes the line 'How can we dance when our earth is turning'?", "Beds Are Burning", ["Blue Sky Mine", "Power and the Passion", "The Dead Heart"]],
    ["Which Midnight Oil frontman later became a federal politician?", "Peter Garrett", ["Rob Hirst", "Jim Moginie", "Martin Rotsey"]],
    ["Which singer had a major hit with 'You're the Voice'?", "John Farnham", ["Daryl Braithwaite", "Jimmy Barnes", "Russell Morris"]],
    ["Which country singer recorded 'A Pub With No Beer'?", "Slim Dusty", ["Troy Cassar-Daley", "Lee Kernaghan", "John Williamson"]],
    ["Which Paul Kelly song begins with a woman catching a bus from Adelaide?", "To Her Door", ["From Little Things Big Things Grow", "Dumb Things", "Before Too Long"]],
    ["Which Australian singer first became famous playing Charlene on 'Neighbours'?", "Kylie Minogue", ["Delta Goodrem", "Natalie Imbruglia", "Tina Arena"]],
    ["Which Kylie Minogue song opens with a famous 'la la la' hook?", "Can't Get You Out of My Head", ["Spinning Around", "The Loco-Motion", "Better the Devil You Know"]],
    ["Which artist released the song 'Chandelier'?", "Sia", ["Kimbra", "Tones and I", "Missy Higgins"]],
    ["Which Australian artist had a global hit with 'Somebody That I Used to Know'?", "Gotye", ["Vance Joy", "Flume", "Troye Sivan"]],
    ["Which New Zealand-born singer featured on Gotye's 'Somebody That I Used to Know'?", "Kimbra", ["Lorde", "Bic Runga", "Ladyhawke"]],
    ["Which project is led by Kevin Parker?", "Tame Impala", ["Empire of the Sun", "Peking Duk", "Rufus Du Sol"]],
    ["Which Australian producer won a Grammy for the album 'Skin'?", "Flume", ["Fisher", "Timmy Trumpet", "What So Not"]],
    ["Which Vance Joy song mentions a riptide?", "Riptide", ["Georgia", "Fire and the Flood", "Mess Is Mine"]],
    ["Which children's group originally included Anthony, Murray, Greg, and Jeff?", "The Wiggles", ["Hi-5", "The Hooley Dooleys", "The Fairies"]],
    ["Which original Wiggle wears blue?", "Anthony Field", ["Murray Cook", "Greg Page", "Jeff Fatt"]],
    ["Which Brisbane band released 'My Happiness'?", "Powderfinger", ["Silverchair", "Grinspoon", "The Living End"]],
    ["Which band from Newcastle released 'Tomorrow' while still teenagers?", "Silverchair", ["Powderfinger", "Jet", "Eskimo Joe"]],
    ["Which Australian band released 'Friday on My Mind'?", "The Easybeats", ["The Angels", "Daddy Cool", "Skyhooks"]],
    ["Which band released the Australian classic 'Eagle Rock'?", "Daddy Cool", ["Sherbet", "Cold Chisel", "Dragon"]],
    ["Which Cold Chisel song mentions Khe Sanh?", "Khe Sanh", ["Flame Trees", "Cheap Wine", "Bow River"]],
    ["Who was the lead singer of Cold Chisel?", "Jimmy Barnes", ["Ian Moss", "Don Walker", "Mossy Cade"]],
    ["Which Yothu Yindi song became an anthem for reconciliation?", "Treaty", ["Solid Rock", "My Island Home", "Blackfella/Whitefella"]],
    ["Which band recorded 'Solid Rock'?", "Goanna", ["Yothu Yindi", "Midnight Oil", "Hunters & Collectors"]],
    ["Which Australian Crawl song begins 'Meet me down by the jetty landing'?", "Reckless", ["The Boys Light Up", "Downhearted", "Errol"]],
    ["Which band recorded 'Throw Your Arms Around Me'?", "Hunters & Collectors", ["Mental As Anything", "The Church", "The Triffids"]],
    ["Which band released 'Sweet Disposition'?", "The Temper Trap", ["Empire of the Sun", "Pnau", "Cut Copy"]],
    ["Which duo released 'Walking on a Dream'?", "Empire of the Sun", ["Angus & Julia Stone", "Savage Garden", "Rufus Du Sol"]],
    ["Which sibling duo released 'Big Jet Plane'?", "Angus & Julia Stone", ["The Veronicas", "The Presets", "The Waifs"]],
    ["Which INXS song shares its title with a line meaning 'never separate us'?", "Never Tear Us Apart", ["Need You Tonight", "Original Sin", "Mystify"]],
    ["Which Icehouse song is an Australian anthem about the land?", "Great Southern Land", ["Electric Blue", "Crazy", "Hey Little Girl"]],
    ["Which Brisbane duo released 'Truly Madly Deeply'?", "Savage Garden", ["Air Supply", "Bachelor Girl", "Taxiride"]],
    ["Which Tina Arena song includes the chorus 'You're in chains'?", "Chains", ["Sorrento Moon", "Burn", "Heaven Help My Heart"]],
    ["Who won the first season of 'Australian Idol'?", "Guy Sebastian", ["Shannon Noll", "Anthony Callea", "Wes Carr"]],
    ["Which Divinyls song became an international hit in 1991?", "I Touch Myself", ["Boys in Town", "Pleasure and Pain", "Science Fiction"]],
    ["Which band recorded 'Am I Ever Gonna See Your Face Again'?", "The Angels", ["The Saints", "Radio Birdman", "Rose Tattoo"]],
    ["Which Christine Anu song is strongly associated with the Torres Strait Islands?", "My Island Home", ["Party", "Sunshine on a Rainy Day", "Come On"]],
    ["Which Archie Roach song tells the story of the Stolen Generations?", "Took the Children Away", ["Charcoal Lane", "From Little Things Big Things Grow", "Black Smoke"]],
    ["Which Kate Miller-Heidke song represented Australia at Eurovision 2019?", "Zero Gravity", ["The Last Day on Earth", "Caught in the Crowd", "Words"]],
    ["The ARIA Awards recognise achievement in which field?", "Australian music", ["Australian film", "Australian television", "Australian sport"]],
    ["Triple J's Hottest 100 is usually a countdown of what?", "Songs voted by listeners", ["Albums chosen by critics", "Concert venues", "Music videos"]],
    ["Which band released 'Under the Milky Way'?", "The Church", ["The Triffids", "The Go-Betweens", "The Saints"]],
    ["Which band released 'Wide Open Road'?", "The Triffids", ["The Church", "The Go-Betweens", "Midnight Oil"]],
    ["Which band released 'Cattle and Cane'?", "The Go-Betweens", ["The Saints", "The Models", "The Reels"]],
    ["Which Australian punk band released '(I'm) Stranded'?", "The Saints", ["Radio Birdman", "The Angels", "The Birthday Party"]],
    ["Which Nick Cave band includes the words 'Bad Seeds' in its name?", "Nick Cave and the Bad Seeds", ["The Birthday Party", "Grinderman", "The Boys Next Door"]],
    ["Which singer released the viral hit 'Dance Monkey'?", "Tones and I", ["Amy Shark", "Montaigne", "G Flip"]]
  ],
  culture: [
    ["Which Danish architect designed the Sydney Opera House?", "Jorn Utzon", ["Harry Seidler", "Walter Burley Griffin", "Glenn Murcutt"]],
    ["What is the nickname of the Sydney Harbour Bridge?", "The Coathanger", ["The Big Arch", "The Iron Rainbow", "The Harbour Ladder"]],
    ["Which fictional street is central to 'Neighbours'?", "Ramsay Street", ["Summer Bay Road", "Fountain Lakes Drive", "Wandin Valley Way"]],
    ["Which fictional coastal town is the setting for 'Home and Away'?", "Summer Bay", ["Ramsay Bay", "Pearl Bay", "Port Niranda"]],
    ["Which Australian city is strongly associated with the children's show 'Bluey'?", "Brisbane", ["Melbourne", "Adelaide", "Hobart"]],
    ["In 'Kath & Kim', what is the family's fictional suburb?", "Fountain Lakes", ["Summer Bay", "Pearl Bay", "Erinsborough"]],
    ["Which actor played Mick Dundee in 'Crocodile Dundee'?", "Paul Hogan", ["Bryan Brown", "Mel Gibson", "Sam Neill"]],
    ["Who directed the original 'Mad Max' film?", "George Miller", ["Peter Weir", "Baz Luhrmann", "Phillip Noyce"]],
    ["Which Australian film features the line 'Tell him he's dreaming'?", "The Castle", ["Muriel's Wedding", "Strictly Ballroom", "Red Dog"]],
    ["Which Australian film stars Toni Collette as a woman from Porpoise Spit?", "Muriel's Wedding", ["The Dressmaker", "Japanese Story", "Looking for Alibrandi"]],
    ["Which Australian film follows drag performers travelling to Alice Springs?", "The Adventures of Priscilla, Queen of the Desert", ["Strictly Ballroom", "The Sapphires", "Bran Nue Dae"]],
    ["Which author wrote 'Cloudstreet'?", "Tim Winton", ["Peter Carey", "Richard Flanagan", "Thomas Keneally"]],
    ["Which Australian writer won the Nobel Prize in Literature in 1973?", "Patrick White", ["David Malouf", "Christina Stead", "Geraldine Brooks"]],
    ["Which major Australian literary prize is named after an author of 'My Brilliant Career'?", "Miles Franklin Award", ["Stella Prize", "Booker Prize", "Prime Minister's Literary Award"]],
    ["'Picnic at Hanging Rock' is set in which Australian state?", "Victoria", ["Tasmania", "Queensland", "Western Australia"]],
    ["Which comedian created Dame Edna Everage?", "Barry Humphries", ["Graham Kennedy", "Paul Hogan", "Shaun Micallef"]],
    ["Who wrote the words to 'Waltzing Matilda'?", "Banjo Paterson", ["Henry Lawson", "Dorothea Mackellar", "C. J. Dennis"]],
    ["Which Australian poet wrote 'The Drover's Wife'?", "Henry Lawson", ["Banjo Paterson", "Judith Wright", "Les Murray"]],
    ["Which bushranger is associated with a homemade suit of armour?", "Ned Kelly", ["Ben Hall", "Captain Thunderbolt", "Moondyne Joe"]],
    ["Which airline is nicknamed 'The Flying Kangaroo'?", "Qantas", ["Virgin Australia", "Jetstar", "Rex"]],
    ["Which museum is known by the acronym MONA?", "Museum of Old and New Art", ["Museum of National Australia", "Melbourne Open National Art", "Modern Oceanic Northern Archive"]],
    ["MONA is located near which Australian city?", "Hobart", ["Darwin", "Canberra", "Perth"]],
    ["The National Gallery of Victoria is in which city?", "Melbourne", ["Sydney", "Adelaide", "Brisbane"]],
    ["Which city hosts the Adelaide Fringe?", "Adelaide", ["Perth", "Canberra", "Darwin"]],
    ["Which film centres on the Parkes radio telescope during the Apollo 11 mission?", "The Dish", ["The Castle", "Crackerjack", "Malcolm"]],
    ["In Australian slang, what does 'arvo' mean?", "Afternoon", ["Breakfast", "Holiday", "Argument"]],
    ["In Australian slang, what is a 'servo'?", "Service station", ["School", "Suburb", "Surfboard"]],
    ["In Australian slang, what is a 'bottle-o'?", "Liquor shop", ["Bakery", "Bottle museum", "Beach kiosk"]],
    ["In Australia, what are 'thongs' usually worn on?", "Feet", ["Hands", "Head", "Wrists"]],
    ["What type of item is an Akubra?", "Hat", ["Boot", "Coat", "Knife"]],
    ["What type of item is a Driza-Bone?", "Coat", ["Hat", "Tent", "Belt"]],
    ["R. M. Williams is especially known for making what?", "Boots", ["Surfboards", "Cricket bats", "Sunglasses"]],
    ["NAIDOC Week celebrates the history and culture of which peoples?", "Aboriginal and Torres Strait Islander peoples", ["Irish Australians", "Greek Australians", "Pacific athletes"]],
    ["Which returning throwing tool is commonly associated with Aboriginal Australian culture?", "Boomerang", ["Woomera", "Didgeridoo", "Nulla nulla"]],
    ["The traditional owners of Uluru are known collectively as what?", "Anangu", ["Noongar", "Kulin", "Palawa"]],
    ["Which constellation appears on the Australian flag?", "Southern Cross", ["Orion", "Scorpius", "Pleiades"]],
    ["In 'Waltzing Matilda', what animal does the swagman steal?", "Jumbuck", ["Kangaroo", "Emu", "Goanna"]],
    ["What is Australia's national anthem?", "Advance Australia Fair", ["Waltzing Matilda", "I Still Call Australia Home", "True Blue"]],
    ["What kind of household item is a Hills Hoist?", "Rotary clothesline", ["Kitchen mixer", "Garden hose", "Mailbox"]],
    ["A Bunnings sausage sizzle is usually sold outside what type of store?", "Hardware store", ["Bookshop", "Cinema", "Pharmacy"]],
    ["What is 'Schoolies' in Australian culture?", "End-of-school celebrations", ["A school uniform brand", "A children's cereal", "A TV quiz show"]],
    ["Which long-running TV drama was set around Wandin Valley?", "A Country Practice", ["Blue Heelers", "All Saints", "Packed to the Rafters"]],
    ["Which children's TV series features a family living in a lighthouse?", "Round the Twist", ["Play School", "Ship to Shore", "The Ferals"]],
    ["Which kangaroo starred in a classic Australian TV series?", "Skippy", ["Blinky Bill", "Bunyip Bluegum", "Fatso"]],
    ["Which beach is central to the TV series 'Bondi Rescue'?", "Bondi Beach", ["Manly Beach", "St Kilda Beach", "Cottesloe Beach"]],
    ["Which Australian cooking show features mystery boxes and pressure tests?", "MasterChef Australia", ["My Kitchen Rules", "Ready Steady Cook", "The Cook Up"]],
    ["Which novel by Melina Marchetta follows Josie Alibrandi?", "Looking for Alibrandi", ["Tomorrow, When the War Began", "Puberty Blues", "Playing Beatie Bow"]],
    ["Which John Marsden novel begins a series about teenagers after an invasion?", "Tomorrow, When the War Began", ["So Much to Tell You", "Blueback", "Lockie Leonard"]],
    ["Which Australian animated koala was created by Dorothy Wall?", "Blinky Bill", ["Snugglepot", "Skippy", "Bunyip Bluegum"]],
    ["Which gumnut babies were created by May Gibbs?", "Snugglepot and Cuddlepie", ["Blinky and Nutsy", "Dot and Dash", "Mim and Pip"]]
  ],
  general: [
    ["How many states does Australia have?", "Six", ["Five", "Seven", "Eight"]],
    ["What is the capital city of Australia?", "Canberra", ["Sydney", "Melbourne", "Brisbane"]],
    ["Which is Australia's largest state by area?", "Western Australia", ["Queensland", "South Australia", "New South Wales"]],
    ["Which Australian state is an island?", "Tasmania", ["Victoria", "Queensland", "South Australia"]],
    ["What is Australia's longest river?", "Murray River", ["Darling River", "Murrumbidgee River", "Lachlan River"]],
    ["What is Australia's highest mountain?", "Mount Kosciuszko", ["Mount Bogong", "Mount Ossa", "Cradle Mountain"]],
    ["The Great Barrier Reef lies off the coast of which state?", "Queensland", ["Western Australia", "Victoria", "Tasmania"]],
    ["Kakadu National Park is in which territory?", "Northern Territory", ["Australian Capital Territory", "Jervis Bay Territory", "Norfolk Island"]],
    ["What type of animal is a dingo?", "Wild dog", ["Wild cat", "Small kangaroo", "Large lizard"]],
    ["Which Australian animal is a monotreme?", "Platypus", ["Koala", "Wombat", "Possum"]],
    ["Which spiny Australian animal is also a monotreme?", "Echidna", ["Bilby", "Quokka", "Bandicoot"]],
    ["Which two animals appear on the Australian coat of arms?", "Kangaroo and emu", ["Koala and wombat", "Dingo and platypus", "Crocodile and cassowary"]],
    ["What do koalas mainly eat?", "Eucalyptus leaves", ["Wattle seeds", "Spinifex grass", "Banksia flowers"]],
    ["Which island near Perth is famous for quokkas?", "Rottnest Island", ["Kangaroo Island", "Phillip Island", "Bruny Island"]],
    ["What does the name 'Nullarbor' refer to?", "No trees", ["Red desert", "Long road", "Salt lake"]],
    ["Australia changed to decimal currency in which year?", "1966", ["1956", "1976", "1986"]],
    ["What is Australia's currency?", "Australian dollar", ["Australian pound", "Australian euro", "Australian crown"]],
    ["Where is Parliament House located?", "Canberra", ["Sydney", "Melbourne", "Adelaide"]],
    ["What is the official Canberra residence of the Prime Minister called?", "The Lodge", ["Yarralumla House", "Kirribilli House", "Government Cottage"]],
    ["Which court is the highest court in Australia's judicial system?", "High Court of Australia", ["Federal Court", "Supreme Court of NSW", "Family Court"]],
    ["The Governor-General represents whom in Australia?", "The monarch", ["The Prime Minister", "The Chief Justice", "The Senate"]],
    ["The First Fleet arrived in 1788 at which harbour?", "Sydney Harbour", ["Port Phillip Bay", "Moreton Bay", "Botany Bay only"]],
    ["In which year did Australia federate?", "1901", ["1788", "1851", "1914"]],
    ["On what date is Anzac Day observed?", "25 April", ["1 January", "26 January", "11 November"]],
    ["On what date is Australia Day marked nationally?", "26 January", ["25 April", "1 May", "3 September"]],
    ["The Eureka Stockade took place near which Victorian city?", "Ballarat", ["Bendigo", "Geelong", "Shepparton"]],
    ["Which service provides medical care to remote parts of Australia by air?", "Royal Flying Doctor Service", ["St John Air", "Outback Rescue Corps", "Australian Air Ambulance League"]],
    ["Where is the Royal Australian Mint located?", "Canberra", ["Perth", "Melbourne", "Sydney"]],
    ["Which Australian invented the flight data recorder known as the black box?", "David Warren", ["Howard Florey", "Graeme Clark", "John Monash"]],
    ["Which Australian scientist is strongly associated with the multi-channel cochlear implant?", "Graeme Clark", ["David Warren", "Howard Florey", "Elizabeth Blackburn"]],
    ["Which Australian scientist shared a Nobel Prize for work on penicillin?", "Howard Florey", ["Mark Oliphant", "Macfarlane Burnet", "Frank Fenner"]],
    ["Which chocolate biscuit is often used in a 'slam' with a hot drink?", "Tim Tam", ["Mint Slice", "Monte Carlo", "Iced VoVo"]],
    ["Which malted drink powder was developed in Australia in the 1930s?", "Milo", ["Ovaltine", "Nesquik", "Horlicks"]],
    ["Which city is the capital of Queensland?", "Brisbane", ["Cairns", "Townsville", "Gold Coast"]],
    ["Which city is the capital of South Australia?", "Adelaide", ["Whyalla", "Mount Gambier", "Port Augusta"]],
    ["Which city is the capital of Western Australia?", "Perth", ["Fremantle", "Bunbury", "Albany"]],
    ["Which city is the capital of Tasmania?", "Hobart", ["Launceston", "Devonport", "Burnie"]],
    ["Which city is the capital of the Northern Territory?", "Darwin", ["Alice Springs", "Katherine", "Tennant Creek"]],
    ["Which city is the capital of Victoria?", "Melbourne", ["Geelong", "Ballarat", "Bendigo"]],
    ["Which city is the capital of New South Wales?", "Sydney", ["Newcastle", "Wollongong", "Parramatta"]],
    ["The Ghan rail journey runs between Adelaide and which northern city?", "Darwin", ["Cairns", "Broome", "Townsville"]],
    ["The Indian Pacific rail journey runs between Sydney and which western city?", "Perth", ["Adelaide", "Darwin", "Hobart"]],
    ["The Great Ocean Road is in which state?", "Victoria", ["Queensland", "Western Australia", "Tasmania"]],
    ["The Twelve Apostles are primarily what kind of natural feature?", "Limestone stacks", ["Granite peaks", "Coral reefs", "Sand dunes"]],
    ["Which South Australian town is famous for underground homes and opal mining?", "Coober Pedy", ["Roxby Downs", "Port Pirie", "Renmark"]],
    ["Australia lies mainly in which hemisphere?", "Southern Hemisphere", ["Northern Hemisphere", "Eastern polar region", "Western polar region"]],
    ["Which line of latitude crosses Australia?", "Tropic of Capricorn", ["Equator", "Tropic of Cancer", "Arctic Circle"]],
    ["What is Australia's emergency phone number?", "000", ["111", "911", "999"]],
    ["What is Australia's international telephone country code?", "+61", ["+64", "+44", "+1"]],
    ["What is Australia's internet country-code domain?", ".au", [".oz", ".aus", ".aust"]]
  ]
};

export const QUESTION_BANK = Object.entries(QUESTION_SETS).flatMap(([category, rows]) =>
  rows.map(([question, answer, distractors], index) => {
    const id = `${category}-${String(index + 1).padStart(3, "0")}`;
    return {
      id,
      category,
      question,
      options: rotateOptions([answer, ...distractors], index),
      answer
    };
  })
);

function rotateOptions(options, index) {
  const offset = index % options.length;
  return [...options.slice(offset), ...options.slice(0, offset)];
}
